### ISSUE TITLE
Error:This game is not compatiable with this console！

### ISSUE THREAD

**Issue by hualazimo7** [ClusterM/coolgirl-famicom-multicart#18]
My console is a third-party retro machine，which works well with the coolboy cartridge written by your dumper .

And then I made A coolgirl one ,while it can not enter any game of the multi-roms, with the error "This game is not compatiable with this console！"

But this console is suitable with Everdrive N8 Flash cart， so it's weird.!

**Comment by ClusterM** [comment]
Hi! Can you share your config and used command line options?

**Comment by hualazimo7** [comment]
Hi! I just used the default config file for the EPM, and write the coolgirl cart by the old version dumper, with command " write-coolgirl --file multiroms.nes

**Comment by hualazimo7** [comment]
The multirom.nes was built by "coolgirl multirom builder"

**Comment by hualazimo7** [comment]
![IMG_20240109_185240.jpg](https://github.com/ClusterM/coolgirl-famicom-multicart/assets/74229525/19e47083-3443-45fe-9e54-507b25ec79e8)
There is another problem, menu can not show any words, you see, game titles are blue blanks， I cant understand this.

**Comment by ClusterM** [comment]
Which builder version are you using? And which platform/system? Please try the latest interim version of the builder. Seems like some files are corrupted or wrong.

**Comment by ClusterM** [comment]
Any news?

**Comment by hualazimo7** [comment]
Pity, it still can not work. My dump-writer is the old version one, while the process of programming seemed successful. All toolchains' updated to the latest version.
Oh, futhermore, I have no idea with linux os, so I just programmed the cart with cmd command line, something must happened when the cart was programming, hardware or software.
Maybe I should test it on the newest dumper?

**Comment by ClusterM** [comment]
Please answer the questions.

**Comment by hualazimo7** [comment]
Rom builder : v2.0b
Dumper writer client :  v3.4
Emulator: Fceux work
System: Windows10

**Comment by ClusterM** [comment]
Can you share the ROM? You can email it to cluster@cluster.wtf.
Or you can share the thole builder directory if you can.

**Comment by hualazimo7** [comment]
Sent seconds ago, thanks.

**Comment by ClusterM** [comment]
> Sent seconds ago, thanks.

Weird. Can you send me the whore builder directory?
