### ISSUE TITLE
HELP MR CLUSTER QUARTUS II ERROR in EPM1270T144 

### ISSUE THREAD

**Issue by darleiv** [ClusterM/coolgirl-famicom-multicart#4]
Error: Peak virtual memory: 235 megabytes

when I use the EPM1270T144 in the quartus it returns this error Error: Peak virtual memory: 235 megabytes, what can it be? because if I select a more powerful one, but it doesn't match your scheme

**Comment by darleiv** [comment]
https://ibb.co/SXdg1Lx

**Comment by darleiv** [comment]
когда я использую EPM1270T144 в квартусе, он возвращает эту ошибку Ошибка: Пиковая виртуальная память: 235 мегабайт, что это может быть? потому что, если я выберу более мощный, но он не соответствует вашей схеме
https://ibb.co/SXdg1Lx epm2210 компилирует это не

**Comment by ClusterM** [comment]
I have no idea :( Which version of Quartus are you using?

**Comment by darleiv** [comment]
hello cluster; Should be it. I noticed that you used Quartus 17 Lite. I use 8.1 kkk

привет кластер; Должно быть так. Я заметил, что вы использовали Quartus 17 Lite. Я использую 8.1 ккк

Я опустил 17 на лоб
