### ISSUE TITLE
millimeter of the plate important question

### ISSUE THREAD

**Issue by darleiv** [ClusterM/coolgirl-famicom-multicart#8]
large enema your plate is 6 mm at this angle. and I measured some and they measure 7mm made by farid .. nes dev. which is the ideal 6mm or 7mm? note in the photo where I mean
https://ibb.co/s9FDVRD
https://ibb.co/zsGZ9Ct
https://ibb.co/J3mV4vs
https://ibb.co/RC80XmF
https://ibb.co/8j9QXxT

**Comment by ClusterM** [comment]
I think that it's not important because the circuit board is retained by the pass.
