### ISSUE TITLE
CoolGirl_config.vh CoolGirl_mappers.vh

### ISSUE THREAD

**Issue by darleiv** [ClusterM/coolgirl-famicom-multicart#9]
these two files are where friend

**Comment by ClusterM** [comment]
In the root:
https://github.com/coolgirl-multicart/coolgirl-famicom-multicart/blob/master/CoolGirl_config.vh
https://github.com/coolgirl-multicart/coolgirl-famicom-multicart/blob/master/CoolGirl_mappers.vh
